### ISSUE TITLE
How are the foldout-messages are displayed in Mario Party 2?

### ISSUE THREAD

**Issue by Pelikuni** [PartyPlanner64/symbols#2]
A couple of friends of mine are trying to help me make a simple event (give player 5 coins) with text for MP2, but we cannot find where the functions for the event messages exist. There are no leads on the FAQ either. Verbatim from my friend - "The best lead I have is to deconstruct the existing events that use that (Koopa Bank being the biggest example) - but I cannot find where those functions exist (as referenced by the event)." If you have any idea where it's located, please respond or email me ASAP!

**Comment by PartyPlanner64** [comment]
The Koopa Bank function in Western Land is at 0x80010964C. I haven't tested it, but I think this is the string showing function.

    80056368,code,stringwindowshow?,A0=character_index,A1=string index,A2 onward: string format options

The giveaway is all the stack locations it manipulates prior to calling it (the string formatting entries). There may be other functions nearby that need to be called to make it work. Like the other games, it also probably supports a string pointer for A1.
